### ISSUE TITLE
Ability to change starting note for each row.

### ISSUE THREAD

**Issue by seabre** [rogerallen/GridStrument#8]
Adding the ability to set a starting note for each row would allow the player to play in different tunings:
- http://en.wikipedia.org/wiki/Guitar_tunings
- http://www.stick.com/articles/poorman_tunings/

**Comment by rogerallen** [comment]
Sure thing.  Thanks for the pointers.

**Comment by rogerallen** [comment]
With checkin 9e75bfc1461106c12da39937b12657926b726e1b this should be working now.  Use the "Tuning..." dialog box and set the starting note for each row.

There are 7 rows on my SHIELD.  I can only see 6, but there is probably a tiny sliver of a note underneath the menu bar.  So, you might have to set the value for a note that you can't actually play...

Hopefully solving issue #7 will resolve this, though.

Thanks for the feedback & I hope this works for you.
